### ISSUE TITLE
Can it go upward from 3.0.0 to 3.1.0?

### ISSUE THREAD

**Issue by inayet** [apiture/openapi-down-convert#8]
Hi, Can it go upward from 3.0.0 to 3.1.0? I can't seem to find any solution that takes care of that programmatically

**Comment by DavidBiesack** [comment]
@inayet this tool won't go in that direction.

Please see [this guide](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0).

I did not have the need for this conversion, but feel free to fork or submit a PR - most of this code can be updated to
"go the other direction", although likely it would be another tool since this tool's name is unidirectional :-)

APIMatic supports this conversion from 3.0 to 3.1, but it's not OSS CLI.
